export default [
	{
		"ACTIVIDAD": "SENTADO EN REPOSO",
		"APLICACIONES_TIPICAS": "TEATRO CINE",
		"CALOR": "CALOR TOTAL POR ADULTO MASCULINO",
		"WATTS": "115",
		"BTUH": "400",
		"KCAL/H": "100",
		"": "%"
	},
	{
		"ACTIVIDAD": "SENTADO, TRABAJO MUY LIGERO ESCRITURA",
		"APLICACIONES_TIPICAS": "OFICINAS, HOTELES , APARTAMENTOS",
		"CALOR": "CALOR TOTAL POR ADULTO MASCULINO",
		"WATTS": "140",
		"BTUH": "480",
		"KCAL/H": "120",
		"": "%"
	},
	{
		"ACTIVIDAD": "SENTADO, COMIENDO",
		"APLICACIONES_TIPICAS": "RESTAURANTES",
		"CALOR": "CALOR TOTAL POR ADULTO MASCULINO",
		"WATTS": "150",
		"BTUH": "520",
		"KCAL/H": "130",
		"": ""
	},
	{
		"ACTIVIDAD": "SENTADO, TRABAJANDO LIGERO MECANOGRAFIA",
		"APLICACIONES_TIPICAS": "OFICINAS, HOTELES , APARTAMENTOS",
		"CALOR": "CALOR TOTAL POR ADULTO MASCULINO",
		"WATTS": "185",
		"BTUH": "640",
		"KCAL/H": "160",
		"": ""
	},
	{
		"ACTIVIDAD": "PARADO, TRABAJO LIGERO O CAMINA DESPACIO",
		"APLICACIONES_TIPICAS": "TIENDAS MINORISTAS, BANCOS",
		"CALOR": "CALOR TOTAL POR ADULTO MASCULINO",
		"WATTS": "235",
		"BTUH": "800",
		"KCAL/H": "200",
		"": "12000"
	},
	{
		"ACTIVIDAD": "TRABAJO LIGERO BANCO CAMINADO 3 MPH TRABAJO LIBRO",
		"APLICACIONES_TIPICAS": "FABRICAS",
		"CALOR": "CALOR TOTAL POR ADULTO MASCULINO",
		"WATTS": "255",
		"BTUH": "880",
		"KCAL/H": "220",
		"": "400"
	},
	{
		"ACTIVIDAD": "TRABAJO CON MAQUINAS PESADAS BOLICHE",
		"APLICACIONES_TIPICAS": "FABRICAS",
		"CALOR": "CALOR TOTAL POR ADULTO MASCULINO",
		"WATTS": "305",
		"BTUH": "1040",
		"KCAL/H": "260",
		"": ""
	},
	{
		"ACTIVIDAD": "BOLICHE",
		"APLICACIONES_TIPICAS": "BOLICHE",
		"CALOR": "CALOR TOTAL POR ADULTO MASCULINO",
		"WATTS": "350",
		"BTUH": "1200",
		"KCAL/H": "300",
		"": ""
	},
	{
		"ACTIVIDAD": "BAILE MODERADO",
		"APLICACIONES_TIPICAS": "SALON DE BAILE",
		"CALOR": "CALOR TOTAL POR ADULTO MASCULINO",
		"WATTS": "400",
		"BTUH": "1360",
		"KCAL/H": "340",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO PESADO, TRABAJO CON MAQUINAS PESADAS, LEVANTAR PESAS FABRICAS",
		"APLICACIONES_TIPICAS": "FABRICAS",
		"CALOR": "CALOR TOTAL POR ADULTO MASCULINO",
		"WATTS": "470",
		"BTUH": "1600",
		"KCAL/H": "400",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO PESADO, EJECICIOS ATLETICOS",
		"APLICACIONES_TIPICAS": "GIMNASIO",
		"CALOR": "CALOR TOTAL POR ADULTO MASCULINO",
		"WATTS": "585",
		"BTUH": "2000",
		"KCAL/H": "500",
		"": ""
	},
	{
		"ACTIVIDAD": "SENTADO EN REPOSO",
		"APLICACIONES_TIPICAS": "TEATRO CINE",
		"CALOR": "CALOR TOTAL AJUSTADO",
		"WATTS": "100",
		"BTUH": "350",
		"KCAL/H": "90",
		"": ""
	},
	{
		"ACTIVIDAD": "SENTADO, TRABAJO MUY LIGERO ESCRITURA",
		"APLICACIONES_TIPICAS": "OFICINAS, HOTELES , APARTAMENTOS",
		"CALOR": "CALOR TOTAL AJUSTADO",
		"WATTS": "120",
		"BTUH": "420",
		"KCAL/H": "105",
		"": ""
	},
	{
		"ACTIVIDAD": "SENTADO, COMIENDO",
		"APLICACIONES_TIPICAS": "RESTAURANTES",
		"CALOR": "CALOR TOTAL AJUSTADO",
		"WATTS": "170",
		"BTUH": "580",
		"KCAL/H": "145",
		"": ""
	},
	{
		"ACTIVIDAD": "SENTADO, TRABAJANDO LIGERO MECANOGRAFIA",
		"APLICACIONES_TIPICAS": "OFICINAS, HOTELES , APARTAMENTOS",
		"CALOR": "CALOR TOTAL AJUSTADO",
		"WATTS": "150",
		"BTUH": "510",
		"KCAL/H": "130",
		"": ""
	},
	{
		"ACTIVIDAD": "PARADO, TRABAJO LIGERO O CAMINA DESPACIO",
		"APLICACIONES_TIPICAS": "TIENDAS MINORISTAS, BANCOS",
		"CALOR": "CALOR TOTAL AJUSTADO",
		"WATTS": "185",
		"BTUH": "640",
		"KCAL/H": "160",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO LIGERO BANCO CAMINADO 3 MPH TRABAJO LIBRO",
		"APLICACIONES_TIPICAS": "FABRICAS",
		"CALOR": "CALOR TOTAL AJUSTADO",
		"WATTS": "230",
		"BTUH": "780",
		"KCAL/H": "195",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO CON MAQUINAS PESADAS BOLICHE",
		"APLICACIONES_TIPICAS": "FABRICAS",
		"CALOR": "CALOR TOTAL AJUSTADO",
		"WATTS": "305",
		"BTUH": "1040",
		"KCAL/H": "260",
		"": ""
	},
	{
		"ACTIVIDAD": "BOLICHE",
		"APLICACIONES_TIPICAS": "BOLICHE",
		"CALOR": "CALOR TOTAL AJUSTADO",
		"WATTS": "280",
		"BTUH": "960",
		"KCAL/H": "240",
		"": ""
	},
	{
		"ACTIVIDAD": "BAILE MODERADO",
		"APLICACIONES_TIPICAS": "SALON DE BAILE",
		"CALOR": "CALOR TOTAL AJUSTADO",
		"WATTS": "375",
		"BTUH": "1280",
		"KCAL/H": "320",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO PESADO, TRABAJO CON MAQUINAS PESADAS, LEVANTAR PESAS FABRICAS",
		"APLICACIONES_TIPICAS": "FABRICAS",
		"CALOR": "CALOR TOTAL AJUSTADO",
		"WATTS": "470",
		"BTUH": "1600",
		"KCAL/H": "400",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO PESADO, EJECICIOS ATLETICOS",
		"APLICACIONES_TIPICAS": "GIMNASIO",
		"CALOR": "CALOR TOTAL AJUSTADO",
		"WATTS": "525",
		"BTUH": "1800",
		"KCAL/H": "450",
		"": ""
	},
	{
		"ACTIVIDAD": "SENTADO EN REPOSO",
		"APLICACIONES_TIPICAS": "TEATRO CINE",
		"CALOR": "CALOR SENSIBLE",
		"WATTS": "60",
		"BTUH": "210",
		"KCAL/H": "55",
		"": ""
	},
	{
		"ACTIVIDAD": "SENTADO, TRABAJO MUY LIGERO ESCRITURA",
		"APLICACIONES_TIPICAS": "OFICINAS, HOTELES , APARTAMENTOS",
		"CALOR": "CALOR SENSIBLE",
		"WATTS": "65",
		"BTUH": "230",
		"KCAL/H": "55",
		"": ""
	},
	{
		"ACTIVIDAD": "SENTADO, COMIENDO",
		"APLICACIONES_TIPICAS": "RESTAURANTES",
		"CALOR": "CALOR SENSIBLE",
		"WATTS": "75",
		"BTUH": "255",
		"KCAL/H": "60",
		"": ""
	},
	{
		"ACTIVIDAD": "SENTADO, TRABAJANDO LIGERO MECANOGRAFIA",
		"APLICACIONES_TIPICAS": "OFICINAS, HOTELES , APARTAMENTOS",
		"CALOR": "CALOR SENSIBLE",
		"WATTS": "75",
		"BTUH": "255",
		"KCAL/H": "60",
		"": ""
	},
	{
		"ACTIVIDAD": "PARADO, TRABAJO LIGERO O CAMINA DESPACIO",
		"APLICACIONES_TIPICAS": "TIENDAS MINORISTAS, BANCOS",
		"CALOR": "CALOR SENSIBLE",
		"WATTS": "90",
		"BTUH": "315",
		"KCAL/H": "80",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO LIGERO BANCO CAMINADO 3 MPH TRABAJO LIBRO",
		"APLICACIONES_TIPICAS": "FABRICAS",
		"CALOR": "CALOR SENSIBLE",
		"WATTS": "100",
		"BTUH": "345",
		"KCAL/H": "90",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO CON MAQUINAS PESADAS BOLICHE",
		"APLICACIONES_TIPICAS": "FABRICAS",
		"CALOR": "CALOR SENSIBLE",
		"WATTS": "100",
		"BTUH": "345",
		"KCAL/H": "90",
		"": ""
	},
	{
		"ACTIVIDAD": "BOLICHE",
		"APLICACIONES_TIPICAS": "BOLICHE",
		"CALOR": "CALOR SENSIBLE",
		"WATTS": "100",
		"BTUH": "345",
		"KCAL/H": "90",
		"": ""
	},
	{
		"ACTIVIDAD": "BAILE MODERADO",
		"APLICACIONES_TIPICAS": "SALON DE BAILE",
		"CALOR": "CALOR SENSIBLE",
		"WATTS": "120",
		"BTUH": "405",
		"KCAL/H": "100",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO PESADO, TRABAJO CON MAQUINAS PESADAS, LEVANTAR PESAS FABRICAS",
		"APLICACIONES_TIPICAS": "FABRICAS",
		"CALOR": "CALOR SENSIBLE",
		"WATTS": "165",
		"BTUH": "565",
		"KCAL/H": "140",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO PESADO, EJECICIOS ATLETICOS",
		"APLICACIONES_TIPICAS": "GIMNASIO",
		"CALOR": "CALOR SENSIBLE",
		"WATTS": "185",
		"BTUH": "635",
		"KCAL/H": "160",
		"": ""
	},
	{
		"ACTIVIDAD": "SENTADO EN REPOSO",
		"APLICACIONES_TIPICAS": "TEATRO CINE",
		"CALOR": "CALOR LATENTE",
		"WATTS": "40",
		"BTUH": "140",
		"KCAL/H": "30",
		"": ""
	},
	{
		"ACTIVIDAD": "SENTADO, TRABAJO MUY LIGERO ESCRITURA",
		"APLICACIONES_TIPICAS": "OFICINAS, HOTELES , APARTAMENTOS",
		"CALOR": "CALOR LATENTE",
		"WATTS": "55",
		"BTUH": "190",
		"KCAL/H": "50",
		"": ""
	},
	{
		"ACTIVIDAD": "SENTADO, COMIENDO",
		"APLICACIONES_TIPICAS": "RESTAURANTES",
		"CALOR": "CALOR LATENTE",
		"WATTS": "95",
		"BTUH": "325",
		"KCAL/H": "80",
		"": ""
	},
	{
		"ACTIVIDAD": "SENTADO, TRABAJANDO LIGERO MECANOGRAFIA",
		"APLICACIONES_TIPICAS": "OFICINAS, HOTELES , APARTAMENTOS",
		"CALOR": "CALOR LATENTE",
		"WATTS": "75",
		"BTUH": "255",
		"KCAL/H": "65",
		"": ""
	},
	{
		"ACTIVIDAD": "PARADO, TRABAJO LIGERO O CAMINA DESPACIO",
		"APLICACIONES_TIPICAS": "TIENDAS MINORISTAS, BANCOS",
		"CALOR": "CALOR LATENTE",
		"WATTS": "95",
		"BTUH": "325",
		"KCAL/H": "80",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO LIGERO BANCO CAMINADO 3 MPH TRABAJO LIBRO",
		"APLICACIONES_TIPICAS": "FABRICAS",
		"CALOR": "CALOR LATENTE",
		"WATTS": "130",
		"BTUH": "435",
		"KCAL/H": "110",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO CON MAQUINAS PESADAS BOLICHE",
		"APLICACIONES_TIPICAS": "FABRICAS",
		"CALOR": "CALOR LATENTE",
		"WATTS": "205",
		"BTUH": "695",
		"KCAL/H": "170",
		"": ""
	},
	{
		"ACTIVIDAD": "BOLICHE",
		"APLICACIONES_TIPICAS": "BOLICHE",
		"CALOR": "CALOR LATENTE",
		"WATTS": "180",
		"BTUH": "615",
		"KCAL/H": "150",
		"": ""
	},
	{
		"ACTIVIDAD": "BAILE MODERADO",
		"APLICACIONES_TIPICAS": "SALON DE BAILE",
		"CALOR": "CALOR LATENTE",
		"WATTS": "255",
		"BTUH": "875",
		"KCAL/H": "220",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO PESADO, TRABAJO CON MAQUINAS PESADAS, LEVANTAR PESAS FABRICAS",
		"APLICACIONES_TIPICAS": "FABRICAS",
		"CALOR": "CALOR LATENTE",
		"WATTS": "300",
		"BTUH": "1035",
		"KCAL/H": "260",
		"": ""
	},
	{
		"ACTIVIDAD": "TRABAJO PESADO, EJECICIOS ATLETICOS",
		"APLICACIONES_TIPICAS": "GIMNASIO",
		"CALOR": "CALOR LATENTE",
		"WATTS": "340",
		"BTUH": "1165",
		"KCAL/H": "290",
		"": ""
	}
]