export default [
  {
    equipo: 'minisplit',
    modelo: 'ESMS092',
    capacidad_BTU: '9000',
    SEER: '2.640',
    datos_electricos: '220_1_60',
    cfm_max: '253',
    conex_liquido: '1/4',
    conex_succion: '3/8',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'minisplit',
    modelo: 'ESMS091',
    capacidad_BTU: '9000',
    SEER: '2.640',
    datos_electricos: '110_1_60',
    cfm_max: '253',
    conex_liquido: '1/4',
    conex_succion: '3/8',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'minisplit',
    modelo: 'ESMS122',
    capacidad_BTU: '12000',
    SEER: '3.520',
    datos_electricos: '220_1_60',
    cfm_max: '312',
    conex_liquido: '1/4',
    conex_succion: '3/8',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'minisplit',
    modelo: 'ESMS121',
    capacidad_BTU: '12000',
    SEER: '3.520',
    datos_electricos: '110_1_60',
    cfm_max: '294',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'minisplit',
    modelo: 'ESMS18',
    capacidad_BTU: '18000',
    SEER: '5.280',
    datos_electricos: '220_1_60',
    cfm_max: '447',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'minisplit',
    modelo: 'ESMS24',
    capacidad_BTU: '24000',
    SEER: '7.040',
    datos_electricos: '220_1_60',
    cfm_max: '647',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'minisplit',
    modelo: 'ESMS36',
    capacidad_BTU: '36000',
    SEER: '10.560',
    datos_electricos: '220_1_60',
    cfm_max: '824',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'minisplit_inverter',
    modelo: 'INMS091',
    capacidad_BTU: '9000',
    SEER: '2.640',
    datos_electricos: '115_1_60',
    cfm_max: '300',
    conex_liquido: '1/4',
    conex_succion: '3/8',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'minisplit_inverter',
    modelo: 'INMS121',
    capacidad_BTU: '12000',
    SEER: '3.520',
    datos_electricos: '115_1_60',
    cfm_max: '400',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'minisplit_inverter',
    modelo: 'INMS092',
    capacidad_BTU: '9000',
    SEER: '2.640',
    datos_electricos: '220_1_60',
    cfm_max: '300',
    conex_liquido: '1/4',
    conex_succion: '3/8',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'minisplit_inverter',
    modelo: 'INMS122',
    capacidad_BTU: '12000',
    SEER: '3.520',
    datos_electricos: '220_1_60',
    cfm_max: '400',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'minisplit_inverter',
    modelo: 'INMS18',
    capacidad_BTU: '18000',
    SEER: '5.279',
    datos_electricos: '220_1_60',
    cfm_max: '600',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'minisplit_inverter',
    modelo: 'INMS24',
    capacidad_BTU: '24000',
    SEER: '7.039',
    datos_electricos: '220_1_60',
    cfm_max: '800',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'fancoil_pisotecho',
    modelo: 'DFT36',
    capacidad_BTU: '36000',
    SEER: '',
    datos_electricos: '203_230_1_60',
    cfm_max: '1200',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'fancoil_pisotecho',
    modelo: 'DFT60',
    capacidad_BTU: '60000',
    SEER: '',
    datos_electricos: '203_230_1_60',
    cfm_max: '2000',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'fancoil_cassete',
    modelo: 'ZFC18',
    capacidad_BTU: '18000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '412',
    conex_liquido: '1/4',
    conex_succion: '5/8',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'fancoil_cassete',
    modelo: 'ZFC24',
    capacidad_BTU: '24000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '706',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'fancoil_cassete',
    modelo: 'ZFC36',
    capacidad_BTU: '36000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1100',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'fancoil_cassete',
    modelo: 'ZFC48',
    capacidad_BTU: '48000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1118',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'fancoil_cassete',
    modelo: 'ZFC60',
    capacidad_BTU: '60000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1120',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'condensador_vertical',
    modelo: 'TCVB24',
    capacidad_BTU: '24000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1206',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'condensador_vertical',
    modelo: 'TCVB36',
    capacidad_BTU: '36000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1766',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'condensador_vertical',
    modelo: 'TCVB48',
    capacidad_BTU: '48000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '3531',
    conex_liquido: '3/8',
    conex_succion: '7/8',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'condensador_vertical',
    modelo: 'TCVB60',
    capacidad_BTU: '60000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '3531',
    conex_liquido: '1/2',
    conex_succion: '7/8',
    marca: 'confortfresh',
    proveedor: 'refrinorte'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'CIAC_R410A',
    capacidad_BTU: '9000',
    SEER: '13',
    datos_electricos: '220_1_60',
    cfm_max: '263',
    conex_liquido: '',
    conex_succion: '',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'CIAC_R410A',
    capacidad_BTU: '12000',
    SEER: '13',
    datos_electricos: '220_1_60',
    cfm_max: '349',
    conex_liquido: '',
    conex_succion: '',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'CIAC_R410A',
    capacidad_BTU: '18000',
    SEER: '13',
    datos_electricos: '220_1_60',
    cfm_max: '459',
    conex_liquido: '',
    conex_succion: '',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'CIAC_R410A',
    capacidad_BTU: '24000',
    SEER: '13',
    datos_electricos: '220_1_60',
    cfm_max: '595',
    conex_liquido: '',
    conex_succion: '',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'XPOWER_SAFIRUS',
    capacidad_BTU: '12000',
    SEER: '24',
    datos_electricos: '220_1_60',
    cfm_max: '441',
    conex_liquido: '1/4',
    conex_succion: '3/8',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'XPOWER_SAFIRUS',
    capacidad_BTU: '18000',
    SEER: '24',
    datos_electricos: '220_1_60',
    cfm_max: '706',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'XPOWER_SAFIRUS',
    capacidad_BTU: '24000',
    SEER: '24',
    datos_electricos: '220_1_60',
    cfm_max: '853',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MNISPLIT',
    modelo: 'XPOWER_BLUE_3',
    capacidad_BTU: '11500',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '348',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MNISPLIT',
    modelo: 'XPOWER_BLUE_4',
    capacidad_BTU: '17000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '505',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MNISPLIT',
    modelo: 'XPOWER_BLUE_5',
    capacidad_BTU: '22000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '600',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MNISPLIT',
    modelo: 'XPOWER_BLUE_6',
    capacidad_BTU: '12000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '301',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'CIAC_INVERTER',
    capacidad_BTU: '12000',
    SEER: '16',
    datos_electricos: '110_1_60',
    cfm_max: '400',
    conex_liquido: '1/4',
    conex_succion: '3/8',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'CIAC_INVERTER',
    capacidad_BTU: '12000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '400',
    conex_liquido: '1/4',
    conex_succion: '3/8',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'CIAC_INVERTER',
    capacidad_BTU: '18000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '600',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'CIAC_INVERTER',
    capacidad_BTU: '24000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '800',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'CIAC_INVERTER',
    capacidad_BTU: '36000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '1200',
    conex_liquido: '1/4',
    conex_succion: '5/8',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'SAMSUNG_DELTA_INVERTER',
    capacidad_BTU: '9000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '300',
    conex_liquido: '',
    conex_succion: '',
    marca: 'SAMSUNG',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'SAMSUNG_DELTA_INVERTER',
    capacidad_BTU: '11000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '367',
    conex_liquido: '',
    conex_succion: '',
    marca: 'SAMSUNG',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'SAMSUNG_DELTA_INVERTER',
    capacidad_BTU: '16500',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '550',
    conex_liquido: '',
    conex_succion: '',
    marca: 'SAMSUNG',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'SAMSUNG_DELTA_INVERTER',
    capacidad_BTU: '20000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '667',
    conex_liquido: '',
    conex_succion: '',
    marca: 'SAMSUNG',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'SAMSUNG_BORACAY_INVERTER',
    capacidad_BTU: '8991',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '300',
    conex_liquido: '',
    conex_succion: '',
    marca: 'SAMSUNG',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'SAMSUNG_BORACAY_INVERTER',
    capacidad_BTU: '11499',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '383',
    conex_liquido: '',
    conex_succion: '',
    marca: 'SAMSUNG',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'SAMSUNG_BORACAY_INVERTER',
    capacidad_BTU: '17999',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '600',
    conex_liquido: '',
    conex_succion: '',
    marca: 'SAMSUNG',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'SAMSUNG_BORACAY_INVERTER',
    capacidad_BTU: '20507',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '684',
    conex_liquido: '',
    conex_succion: '',
    marca: 'SAMSUNG',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'PISOTECHO',
    modelo: 'CIAC',
    capacidad_BTU: '36000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1059',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'PISOTECHO',
    modelo: 'CIAC',
    capacidad_BTU: '48000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1353',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'PISOTECHO',
    modelo: 'CIAC',
    capacidad_BTU: '55000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1353',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'CASSETE',
    modelo: 'CIAC',
    capacidad_BTU: '12000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '382',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'CASSETE',
    modelo: 'CIAC',
    capacidad_BTU: '18000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '500',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'CASSETE',
    modelo: 'CIAC',
    capacidad_BTU: '24000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '735',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'CASSETE',
    modelo: 'CIAC',
    capacidad_BTU: '36000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '912',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'CASSETE',
    modelo: 'CIAC',
    capacidad_BTU: '48000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1000',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'CASSETE',
    modelo: 'CIAC',
    capacidad_BTU: '60000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1412',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'CARRIER',
    proveedor: 'INVERPRIMOS'
  },
  {
    equipo: 'MINISPLIT ',
    modelo: 'MSLSERIES_INVERTER',
    capacidad_BTU: '9000',
    SEER: '21',
    datos_electricos: '220_1_60',
    cfm_max: '294',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'MINISPLIT ',
    modelo: 'MSLSERIES_INVERTER',
    capacidad_BTU: '12000',
    SEER: '21',
    datos_electricos: '220_1_60',
    cfm_max: '294',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'MINISPLIT ',
    modelo: 'MSLSERIES_INVERTER',
    capacidad_BTU: '18000',
    SEER: '21',
    datos_electricos: '220_1_60',
    cfm_max: '500',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'MINISPLIT ',
    modelo: 'MSLSERIES_INVERTER',
    capacidad_BTU: '24000',
    SEER: '21',
    datos_electricos: '220_1_60',
    cfm_max: '618',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'CSA_INVERTER',
    capacidad_BTU: '9000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '264',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'CSA_INVERTER',
    capacidad_BTU: '12000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '294',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'CSA_INVERTER',
    capacidad_BTU: '18000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '470',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'CSA_INVERTER',
    capacidad_BTU: '24000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '529',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'MCC',
    capacidad_BTU: '18000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '553',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'MCC',
    capacidad_BTU: '24000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '706',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'MCC',
    capacidad_BTU: '36000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '1088',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'MCC',
    capacidad_BTU: '48000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '1118',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'MCC',
    capacidad_BTU: '60000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '1118',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'PISOTECHO',
    modelo: 'MUA',
    capacidad_BTU: '24000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '800',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'PISOTECHO',
    modelo: 'MUA',
    capacidad_BTU: '36000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1200',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'PISOTECHO',
    modelo: 'MUA',
    capacidad_BTU: '48000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1600',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'PISOTECHO',
    modelo: 'MUA',
    capacidad_BTU: '60000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '2000',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'PAQUETE',
    modelo: 'CONDENSADO_POR_AIRE',
    capacidad_BTU: '60000',
    SEER: '',
    datos_electricos: '220_3_60',
    cfm_max: '2000',
    conex_liquido: '',
    conex_succion: '',
    marca: 'STARLIGHT',
    proveedor: 'THERMOTAR'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'CASSETTE_INVERTER',
    capacidad_BTU: '12000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '540',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'CASSETTE_INVERTER',
    capacidad_BTU: '18000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '560',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'CASSETTE_INVERTER',
    capacidad_BTU: '24000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '680',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'CASSETTE_INVERTER',
    capacidad_BTU: '36000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '825',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'CASSETTE_INVERTER',
    capacidad_BTU: '48000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1180',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'FANCOIL',
    modelo: 'PISO_TECHO_INVERTER',
    capacidad_BTU: '18000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '935',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'FANCOIL',
    modelo: 'PISO_TECHO_INVERTER',
    capacidad_BTU: '24000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1295',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'FANCOIL',
    modelo: 'PISO_TECHO_INVERTER',
    capacidad_BTU: '36000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1765',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'FANCOIL',
    modelo: 'PISO_TECHO_INVERTER',
    capacidad_BTU: '48000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '2300',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'FANCOIL',
    modelo: 'PISO_TECHO_INVERTER',
    capacidad_BTU: '60000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '2355',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'FANCOIL',
    modelo: 'FANCOIL_INVERTER',
    capacidad_BTU: '12000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '600',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'FANCOIL',
    modelo: 'FANCOIL_INVERTER',
    capacidad_BTU: '18000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '900',
    conex_liquido: '1/4',
    conex_succion: '1/2',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'FANCOIL',
    modelo: 'FANCOIL_INVERTER',
    capacidad_BTU: '24000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1320',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'FANCOIL',
    modelo: 'FANCOIL_INVERTER',
    capacidad_BTU: '36000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1845',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'FANCOIL',
    modelo: 'FANCOIL_INVERTER',
    capacidad_BTU: '48000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '2095',
    conex_liquido: '3/8',
    conex_succion: '5/8',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'FANCOIL',
    modelo: 'FANCOIL_INVERTER',
    capacidad_BTU: '60000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '3665',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'INNOVAIR',
    proveedor: 'ALMACENES_DE_REFRIGERACION'
  },
  {
    equipo: 'PAQUETE ',
    modelo: 'LANDMARK ',
    capacidad_BTU: '24000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '3700',
    conex_liquido: '3/8',
    conex_succion: '3/8',
    marca: 'LENNOX',
    proveedor: 'REFRINORTE'
  },
  {
    equipo: 'PAQUETE ',
    modelo: 'LANDMARK ',
    capacidad_BTU: '30000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '3700',
    conex_liquido: '3/8',
    conex_succion: '3/8',
    marca: 'LENNOX',
    proveedor: 'REFRINORTE'
  },
  {
    equipo: 'PAQUETE ',
    modelo: 'LANDMARK ',
    capacidad_BTU: '36000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '3700',
    conex_liquido: '3/8',
    conex_succion: '3/8',
    marca: 'LENNOX',
    proveedor: 'REFRINORTE'
  },
  {
    equipo: 'PAQUETE ',
    modelo: 'LANDMARK ',
    capacidad_BTU: '48000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '3500',
    conex_liquido: '3/8',
    conex_succion: '3/8',
    marca: 'LENNOX',
    proveedor: 'REFRINORTE'
  },
  {
    equipo: 'PAQUETE ',
    modelo: 'LANDMARK ',
    capacidad_BTU: '60000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '4300',
    conex_liquido: '3/8',
    conex_succion: '3/8',
    marca: 'LENNOX',
    proveedor: 'REFRINORTE'
  },
  {
    equipo: 'PAQUETE',
    modelo: 'SIGMA',
    capacidad_BTU: '60000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '2000',
    conex_liquido: '',
    conex_succion: '',
    marca: 'confortfresh',
    proveedor: 'REFRINORTE'
  },
  {
    equipo: 'PAQUETE',
    modelo: 'SIGMA',
    capacidad_BTU: '60000',
    SEER: '',
    datos_electricos: '220_3_60',
    cfm_max: '2000',
    conex_liquido: '',
    conex_succion: '',
    marca: 'confortfresh',
    proveedor: 'REFRINORTE'
  },
  {
    equipo: 'PAQUETE',
    modelo: 'PAQUETE',
    capacidad_BTU: '24000',
    SEER: '14',
    datos_electricos: '220_1_60',
    cfm_max: '775',
    conex_liquido: '3/8',
    conex_succion: '3/8',
    marca: 'TRANE',
    proveedor: 'LA_CASA_TRANE'
  },
  {
    equipo: 'PAQUETE',
    modelo: 'PAQUETE',
    capacidad_BTU: '36000',
    SEER: '14',
    datos_electricos: '220_1_60',
    cfm_max: '1195',
    conex_liquido: '3/8',
    conex_succion: '3/8',
    marca: 'TRANE',
    proveedor: 'LA_CASA_TRANE'
  },
  {
    equipo: 'PAQUETE',
    modelo: 'PAQUETE',
    capacidad_BTU: '36000',
    SEER: '14',
    datos_electricos: '220_3_60',
    cfm_max: '1195',
    conex_liquido: '3/8',
    conex_succion: '3/8',
    marca: 'TRANE',
    proveedor: 'LA_CASA_TRANE'
  },
  {
    equipo: 'PAQUETE',
    modelo: 'PAQUETE',
    capacidad_BTU: '48000',
    SEER: '14',
    datos_electricos: '220_1_60',
    cfm_max: '1600',
    conex_liquido: '3/8',
    conex_succion: '3/8',
    marca: 'TRANE',
    proveedor: 'LA_CASA_TRANE'
  },
  {
    equipo: 'PAQUETE',
    modelo: 'PAQUETE',
    capacidad_BTU: '48000',
    SEER: '14',
    datos_electricos: '220_3_60',
    cfm_max: '1600',
    conex_liquido: '3/8',
    conex_succion: '3/8',
    marca: 'TRANE',
    proveedor: 'LA_CASA_TRANE'
  },
  {
    equipo: 'PAQUETE',
    modelo: 'PAQUETE',
    capacidad_BTU: '60000',
    SEER: '14',
    datos_electricos: '220_1_60',
    cfm_max: '1800',
    conex_liquido: '3/8',
    conex_succion: '3/8',
    marca: 'TRANE',
    proveedor: 'LA_CASA_TRANE'
  },
  {
    equipo: 'PAQUETE',
    modelo: 'PAQUETE',
    capacidad_BTU: '60000',
    SEER: '14',
    datos_electricos: '220_3_60',
    cfm_max: '1800',
    conex_liquido: '3/8',
    conex_succion: '3/8',
    marca: 'TRANE',
    proveedor: 'LA_CASA_TRANE'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLT_CONVENCIONAL',
    capacidad_BTU: '9000',
    SEER: '10',
    datos_electricos: '220_1_60',
    cfm_max: '300',
    conex_liquido: '',
    conex_succion: '',
    marca: 'TRANE',
    proveedor: 'LA_CASA_TRANE'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLT_CONVENCIONAL',
    capacidad_BTU: '12000',
    SEER: '10',
    datos_electricos: '220_1_60',
    cfm_max: '400',
    conex_liquido: '',
    conex_succion: '',
    marca: 'TRANE',
    proveedor: 'LA_CASA_TRANE'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLT_CONVENCIONAL',
    capacidad_BTU: '12000',
    SEER: '10',
    datos_electricos: '112_1_60',
    cfm_max: '400',
    conex_liquido: '',
    conex_succion: '',
    marca: 'TRANE',
    proveedor: 'LA_CASA_TRANE'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLT_CONVENCIONAL',
    capacidad_BTU: '18000',
    SEER: '10',
    datos_electricos: '220_1_60',
    cfm_max: '600',
    conex_liquido: '',
    conex_succion: '',
    marca: 'TRANE',
    proveedor: 'LA_CASA_TRANE'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLT_CONVENCIONAL',
    capacidad_BTU: '24000',
    SEER: '10',
    datos_electricos: '220_1_60',
    cfm_max: '800',
    conex_liquido: '',
    conex_succion: '',
    marca: 'TRANE',
    proveedor: 'LA_CASA_TRANE'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLT_CONVENCIONAL',
    capacidad_BTU: '30000',
    SEER: '10',
    datos_electricos: '220_1_60',
    cfm_max: '1000',
    conex_liquido: '',
    conex_succion: '',
    marca: 'TRANE',
    proveedor: 'LA_CASA_TRANE'
  },
  {
    equipo: 'MNISPLIT',
    modelo: 'MINISPLIT_INVERTER',
    capacidad_BTU: '12000',
    SEER: '16',
    datos_electricos: '110_1_60',
    cfm_max: '400',
    conex_liquido: '',
    conex_succion: '',
    marca: 'BLUELINE',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'MNISPLIT',
    modelo: 'MINISPLIT_CONVENCIONAL',
    capacidad_BTU: '12000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '400',
    conex_liquido: '',
    conex_succion: '',
    marca: 'BLUELINE',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLIT_INVERTER',
    capacidad_BTU: '18000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '600',
    conex_liquido: '',
    conex_succion: '',
    marca: 'BLUELINE',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLIT_INVERTER',
    capacidad_BTU: '24000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '800',
    conex_liquido: '',
    conex_succion: '',
    marca: 'BLUELINE',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLIT_CONVENCIONAL',
    capacidad_BTU: '36000',
    SEER: '11',
    datos_electricos: '220_1_60',
    cfm_max: '1200',
    conex_liquido: '',
    conex_succion: '',
    marca: 'YORK',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLIT_INVERTER',
    capacidad_BTU: '12000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '400',
    conex_liquido: '',
    conex_succion: '',
    marca: 'YORK',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLIT_CONVENCIONAL',
    capacidad_BTU: '12000',
    SEER: '12',
    datos_electricos: '220_1_60',
    cfm_max: '400',
    conex_liquido: '',
    conex_succion: '',
    marca: 'YORK',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLIT_CONVENCIONAL',
    capacidad_BTU: '12000',
    SEER: '13',
    datos_electricos: '220_1_60',
    cfm_max: '400',
    conex_liquido: '',
    conex_succion: '',
    marca: 'YORK',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLIT_CONVENCIONAL',
    capacidad_BTU: '18000',
    SEER: '16',
    datos_electricos: '220_1_60',
    cfm_max: '600',
    conex_liquido: '',
    conex_succion: '',
    marca: 'YORK',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLIT_CONVENCIONAL',
    capacidad_BTU: '18000',
    SEER: '12',
    datos_electricos: '220_1_60',
    cfm_max: '600',
    conex_liquido: '',
    conex_succion: '',
    marca: 'YORK',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLIT_INVERTER',
    capacidad_BTU: '24000',
    SEER: '17',
    datos_electricos: '220_1_60',
    cfm_max: '800',
    conex_liquido: '',
    conex_succion: '',
    marca: 'YORK',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLIT_CONVENCIONAL',
    capacidad_BTU: '24000',
    SEER: '12',
    datos_electricos: '220_1_60',
    cfm_max: '800',
    conex_liquido: '',
    conex_succion: '',
    marca: 'YORK',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'MINISPLIT',
    modelo: 'MINISPLIT_CONVENCIONAL',
    capacidad_BTU: '9000',
    SEER: '13',
    datos_electricos: '220_1_60',
    cfm_max: '300',
    conex_liquido: '',
    conex_succion: '',
    marca: 'YORK',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'ANDROMEDA',
    capacidad_BTU: '36000',
    SEER: '15',
    datos_electricos: '220_1_60',
    cfm_max: '1861',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'BLUELINE',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'ANDROMEDA',
    capacidad_BTU: '48000',
    SEER: '15',
    datos_electricos: '220_1_60',
    cfm_max: '1938',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'BLUELINE',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'ANDROMEDA',
    capacidad_BTU: '55000',
    SEER: '15',
    datos_electricos: '220_1_60',
    cfm_max: '1889',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'BLUELINE',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'ANDROMEDA',
    capacidad_BTU: '55000',
    SEER: '15',
    datos_electricos: '220_1_60',
    cfm_max: '1756',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'BLUELINE',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'ORION',
    capacidad_BTU: '36000',
    SEER: '10',
    datos_electricos: '220_1_60',
    cfm_max: '1090',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'BLUELINE',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'ORION',
    capacidad_BTU: '48000',
    SEER: '10',
    datos_electricos: '220_1_60',
    cfm_max: '1120',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'BLUELINE',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'ORION',
    capacidad_BTU: '52000',
    SEER: '10',
    datos_electricos: '220_1_60',
    cfm_max: '1120',
    conex_liquido: '3/8',
    conex_succion: '3/4',
    marca: 'BLUELINE',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'YORK',
    capacidad_BTU: '24000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '800',
    conex_liquido: '',
    conex_succion: '',
    marca: 'YORK',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'YORK',
    capacidad_BTU: '36000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1200',
    conex_liquido: '',
    conex_succion: '',
    marca: 'YORK',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'YORK',
    capacidad_BTU: '48000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '1600',
    conex_liquido: '',
    conex_succion: '',
    marca: 'YORK',
    proveedor: 'TRS_PARTES'
  },
  {
    equipo: 'CASSETTE',
    modelo: 'YORK',
    capacidad_BTU: '60000',
    SEER: '',
    datos_electricos: '220_1_60',
    cfm_max: '2000',
    conex_liquido: '',
    conex_succion: '',
    marca: 'YORK',
    proveedor: 'TRS_PARTES'
  }
]
