export default [
	{
		"LATITUD": "0",
		"MES": "DIC",
		"N": "-3",
		"NNE_NNW": "-5",
		"NE NW": "-5",
		"ENE_WNW": "-5",
		"EW": "-2",
		"ESE_WSW": "0",
		"SE_SW": "3",
		"SSE_SSW": "6",
		"S": "9",
		"HORA": "-1"
	},
	{
		"LATITUD": "0",
		"MES": "ENE/NOV",
		"N": "-3",
		"NNE_NNW": "-5",
		"NE NW": "-4",
		"ENE_WNW": "-4",
		"EW": "-1",
		"ESE_WSW": "0",
		"SE_SW": "2",
		"SSE_SSW": "4",
		"S": "7",
		"HORA": "-1"
	},
	{
		"LATITUD": "0",
		"MES": "FEB/OCT",
		"N": "-3",
		"NNE_NNW": "-2",
		"NE NW": "-2",
		"ENE_WNW": "-2",
		"EW": "-1",
		"ESE_WSW": "-1",
		"SE_SW": "0",
		"SSE_SSW": "-1",
		"S": "0",
		"HORA": "0"
	},
	{
		"LATITUD": "0",
		"MES": "MAR/SEP",
		"N": "-3",
		"NNE_NNW": "0",
		"NE NW": "1",
		"ENE_WNW": "-1",
		"EW": "-1",
		"ESE_WSW": "-3",
		"SE_SW": "-3",
		"SSE_SSW": "-5",
		"S": "-8",
		"HORA": "-1"
	},
	{
		"LATITUD": "0",
		"MES": "ABR/AGO",
		"N": "5",
		"NNE_NNW": "4",
		"NE NW": "3",
		"ENE_WNW": "0",
		"EW": "-2",
		"ESE_WSW": "-5",
		"SE_SW": "-6",
		"SSE_SSW": "-8",
		"S": "-8",
		"HORA": "-2"
	},
	{
		"LATITUD": "0",
		"MES": "MAY/JUL",
		"N": "10",
		"NNE_NNW": "7",
		"NE NW": "5",
		"ENE_WNW": "0",
		"EW": "-3",
		"ESE_WSW": "-7",
		"SE_SW": "-8",
		"SSE_SSW": "-9",
		"S": "-8",
		"HORA": "-4"
	},
	{
		"LATITUD": "0",
		"MES": "JUN",
		"N": "12",
		"NNE_NNW": "9",
		"NE NW": "5",
		"ENE_WNW": "0",
		"EW": "-3",
		"ESE_WSW": "-7",
		"SE_SW": "-9",
		"SSE_SSW": "-10",
		"S": "-9",
		"HORA": "-5"
	},
	{
		"LATITUD": "8",
		"MES": "DIC",
		"N": "-4",
		"NNE_NNW": "-6",
		"NE NW": "-6",
		"ENE_WNW": "-6",
		"EW": "-3",
		"ESE_WSW": "0",
		"SE_SW": "4",
		"SSE_SSW": "8",
		"S": "12",
		"HORA": "-5"
	},
	{
		"LATITUD": "8",
		"MES": "ENE/NOV",
		"N": "-3",
		"NNE_NNW": "-5",
		"NE NW": "-6",
		"ENE_WNW": "-5",
		"EW": "-2",
		"ESE_WSW": "0",
		"SE_SW": "3",
		"SSE_SSW": "6",
		"S": "10",
		"HORA": "-4"
	},
	{
		"LATITUD": "8",
		"MES": "FEB/OCT",
		"N": "-3",
		"NNE_NNW": "-4",
		"NE NW": "-3",
		"ENE_WNW": "-3",
		"EW": "-1",
		"ESE_WSW": "-1",
		"SE_SW": "1",
		"SSE_SSW": "2",
		"S": "4",
		"HORA": "-1"
	},
	{
		"LATITUD": "8",
		"MES": "MAR/SEP",
		"N": "-3",
		"NNE_NNW": "-2",
		"NE NW": "-1",
		"ENE_WNW": "-1",
		"EW": "-1",
		"ESE_WSW": "-2",
		"SE_SW": "-2",
		"SSE_SSW": "-3",
		"S": "-4",
		"HORA": "0"
	},
	{
		"LATITUD": "8",
		"MES": "ABR/AGO",
		"N": "2",
		"NNE_NNW": "2",
		"NE NW": "2",
		"ENE_WNW": "0",
		"EW": "-1",
		"ESE_WSW": "-4",
		"SE_SW": "-5",
		"SSE_SSW": "-7",
		"S": "-7",
		"HORA": "-1"
	},
	{
		"LATITUD": "8",
		"MES": "MAY/JUL",
		"N": "7",
		"NNE_NNW": "5",
		"NE NW": "4",
		"ENE_WNW": "0",
		"EW": "-2",
		"ESE_WSW": "-5",
		"SE_SW": "-7",
		"SSE_SSW": "-9",
		"S": "-7",
		"HORA": "-2"
	},
	{
		"LATITUD": "8",
		"MES": "JUN",
		"N": "9",
		"NNE_NNW": "6",
		"NE NW": "4",
		"ENE_WNW": "0",
		"EW": "-2",
		"ESE_WSW": "-6",
		"SE_SW": "-8",
		"SSE_SSW": "-9",
		"S": "-7",
		"HORA": "-2"
	},
	{
		"LATITUD": "16",
		"MES": "DIC",
		"N": "-4",
		"NNE_NNW": "-6",
		"NE NW": "-8",
		"ENE_WNW": "-8",
		"EW": "-4",
		"ESE_WSW": "-1",
		"SE_SW": "4",
		"SSE_SSW": "9",
		"S": "13",
		"HORA": "-9"
	},
	{
		"LATITUD": "16",
		"MES": "ENE/NOV",
		"N": "-4",
		"NNE_NNW": "-6",
		"NE NW": "-7",
		"ENE_WNW": "-7",
		"EW": "-4",
		"ESE_WSW": "-1",
		"SE_SW": "4",
		"SSE_SSW": "8",
		"S": "12",
		"HORA": "-7"
	},
	{
		"LATITUD": "16",
		"MES": "FEB/OCT",
		"N": "-3",
		"NNE_NNW": "-5",
		"NE NW": "-5",
		"ENE_WNW": "-4",
		"EW": "-2",
		"ESE_WSW": "0",
		"SE_SW": "2",
		"SSE_SSW": "5",
		"S": "7",
		"HORA": "-4"
	},
	{
		"LATITUD": "16",
		"MES": "MAR/SEP",
		"N": "-3",
		"NNE_NNW": "-3",
		"NE NW": "-2",
		"ENE_WNW": "-2",
		"EW": "-1",
		"ESE_WSW": "-1",
		"SE_SW": "0",
		"SSE_SSW": "0",
		"S": "0",
		"HORA": "-1"
	},
	{
		"LATITUD": "16",
		"MES": "ABR/AGO",
		"N": "-1",
		"NNE_NNW": "0",
		"NE NW": "-1",
		"ENE_WNW": "-1",
		"EW": "-1",
		"ESE_WSW": "-3",
		"SE_SW": "-3",
		"SSE_SSW": "-5",
		"S": "-6",
		"HORA": "0"
	},
	{
		"LATITUD": "16",
		"MES": "MAY/JUL",
		"N": "4",
		"NNE_NNW": "3",
		"NE NW": "3",
		"ENE_WNW": "0",
		"EW": "-1",
		"ESE_WSW": "-4",
		"SE_SW": "-5",
		"SSE_SSW": "-7",
		"S": "-7",
		"HORA": "0"
	},
	{
		"LATITUD": "16",
		"MES": "JUN",
		"N": "6",
		"NNE_NNW": "4",
		"NE NW": "4",
		"ENE_WNW": "1",
		"EW": "-1",
		"ESE_WSW": "-4",
		"SE_SW": "-6",
		"SSE_SSW": "-8",
		"S": "-7",
		"HORA": "0"
	},
	{
		"LATITUD": "24",
		"MES": "DIC",
		"N": "-5",
		"NNE_NNW": "-7",
		"NE NW": "-9",
		"ENE_WNW": "-10",
		"EW": "-7",
		"ESE_WSW": "-3",
		"SE_SW": "3",
		"SSE_SSW": "9",
		"S": "13",
		"HORA": "-13"
	},
	{
		"LATITUD": "24",
		"MES": "ENE/NOV",
		"N": "-4",
		"NNE_NNW": "-6",
		"NE NW": "-8",
		"ENE_WNW": "-9",
		"EW": "-6",
		"ESE_WSW": "-3",
		"SE_SW": "3",
		"SSE_SSW": "9",
		"S": "13",
		"HORA": "-11"
	},
	{
		"LATITUD": "24",
		"MES": "FEB/OCT",
		"N": "-4",
		"NNE_NNW": "-5",
		"NE NW": "-6",
		"ENE_WNW": "-6",
		"EW": "-3",
		"ESE_WSW": "-1",
		"SE_SW": "3",
		"SSE_SSW": "7",
		"S": "10",
		"HORA": "-7"
	},
	{
		"LATITUD": "24",
		"MES": "MAR/SEP",
		"N": "-3",
		"NNE_NNW": "-4",
		"NE NW": "-3",
		"ENE_WNW": "-3",
		"EW": "-1",
		"ESE_WSW": "-1",
		"SE_SW": "1",
		"SSE_SSW": "2",
		"S": "4",
		"HORA": "-3"
	},
	{
		"LATITUD": "24",
		"MES": "ABR/AGO",
		"N": "-2",
		"NNE_NNW": "-1",
		"NE NW": "0",
		"ENE_WNW": "-1",
		"EW": "-1",
		"ESE_WSW": "-2",
		"SE_SW": "-1",
		"SSE_SSW": "-2",
		"S": "-3",
		"HORA": "0"
	},
	{
		"LATITUD": "24",
		"MES": "MAY/JUL",
		"N": "1",
		"NNE_NNW": "2",
		"NE NW": "2",
		"ENE_WNW": "0",
		"EW": "0",
		"ESE_WSW": "-3",
		"SE_SW": "-3",
		"SSE_SSW": "-5",
		"S": "-6",
		"HORA": "1"
	},
	{
		"LATITUD": "24",
		"MES": "JUN",
		"N": "3",
		"NNE_NNW": "3",
		"NE NW": "3",
		"ENE_WNW": "1",
		"EW": "0",
		"ESE_WSW": "-3",
		"SE_SW": "-4",
		"SSE_SSW": "-6",
		"S": "-6",
		"HORA": "1"
	},
	{
		"LATITUD": "32",
		"MES": "DIC",
		"N": "-5",
		"NNE_NNW": "-7",
		"NE NW": "-10",
		"ENE_WNW": "-11",
		"EW": "-8",
		"ESE_WSW": "-5",
		"SE_SW": "2",
		"SSE_SSW": "9",
		"S": "12",
		"HORA": "-17"
	},
	{
		"LATITUD": "32",
		"MES": "ENE/NOV",
		"N": "-5",
		"NNE_NNW": "-7",
		"NE NW": "-9",
		"ENE_WNW": "-11",
		"EW": "-8",
		"ESE_WSW": "-4",
		"SE_SW": "2",
		"SSE_SSW": "9",
		"S": "12",
		"HORA": "-15"
	},
	{
		"LATITUD": "32",
		"MES": "FEB/OCT",
		"N": "-4",
		"NNE_NNW": "-6",
		"NE NW": "-7",
		"ENE_WNW": "-8",
		"EW": "-4",
		"ESE_WSW": "-2",
		"SE_SW": "4",
		"SSE_SSW": "8",
		"S": "11",
		"HORA": "-10"
	},
	{
		"LATITUD": "32",
		"MES": "MAR/SEP",
		"N": "-3",
		"NNE_NNW": "-4",
		"NE NW": "-4",
		"ENE_WNW": "-4",
		"EW": "-2",
		"ESE_WSW": "-1",
		"SE_SW": "3",
		"SSE_SSW": "5",
		"S": "7",
		"HORA": "-5"
	},
	{
		"LATITUD": "32",
		"MES": "ABR/AGO",
		"N": "-2",
		"NNE_NNW": "-2",
		"NE NW": "-1",
		"ENE_WNW": "-2",
		"EW": "0",
		"ESE_WSW": "-1",
		"SE_SW": "0",
		"SSE_SSW": "1",
		"S": "1",
		"HORA": "-1"
	},
	{
		"LATITUD": "32",
		"MES": "MAY/JUL",
		"N": "1",
		"NNE_NNW": "1",
		"NE NW": "1",
		"ENE_WNW": "0",
		"EW": "0",
		"ESE_WSW": "-1",
		"SE_SW": "-1",
		"SSE_SSW": "-3",
		"S": "-3",
		"HORA": "1"
	},
	{
		"LATITUD": "32",
		"MES": "JUN",
		"N": "1",
		"NNE_NNW": "2",
		"NE NW": "2",
		"ENE_WNW": "1",
		"EW": "0",
		"ESE_WSW": "-2",
		"SE_SW": "-2",
		"SSE_SSW": "-4",
		"S": "-4",
		"HORA": "2"
	},
	{
		"LATITUD": "40",
		"MES": "DIC",
		"N": "-6",
		"NNE_NNW": "-8",
		"NE NW": "-10",
		"ENE_WNW": "-13",
		"EW": "-10",
		"ESE_WSW": "-7",
		"SE_SW": "0",
		"SSE_SSW": "7",
		"S": "10",
		"HORA": "-21"
	},
	{
		"LATITUD": "40",
		"MES": "ENE/NOV",
		"N": "-5",
		"NNE_NNW": "-7",
		"NE NW": "-10",
		"ENE_WNW": "-12",
		"EW": "-9",
		"ESE_WSW": "-6",
		"SE_SW": "1",
		"SSE_SSW": "8",
		"S": "11",
		"HORA": "-19"
	},
	{
		"LATITUD": "40",
		"MES": "FEB/OCT",
		"N": "-5",
		"NNE_NNW": "-7",
		"NE NW": "-8",
		"ENE_WNW": "-9",
		"EW": "-6",
		"ESE_WSW": "-3",
		"SE_SW": "3",
		"SSE_SSW": "8",
		"S": "12",
		"HORA": "-14"
	},
	{
		"LATITUD": "40",
		"MES": "MAR/SEP",
		"N": "-4",
		"NNE_NNW": "-5",
		"NE NW": "-5",
		"ENE_WNW": "-6",
		"EW": "-3",
		"ESE_WSW": "-1",
		"SE_SW": "4",
		"SSE_SSW": "7",
		"S": "10",
		"HORA": "-8"
	},
	{
		"LATITUD": "40",
		"MES": "ABR/AGO",
		"N": "-2",
		"NNE_NNW": "-3",
		"NE NW": "-2",
		"ENE_WNW": "-2",
		"EW": "0",
		"ESE_WSW": "0",
		"SE_SW": "2",
		"SSE_SSW": "3",
		"S": "4",
		"HORA": "-3"
	},
	{
		"LATITUD": "40",
		"MES": "MAY/JUL",
		"N": "0",
		"NNE_NNW": "0",
		"NE NW": "0",
		"ENE_WNW": "0",
		"EW": "0",
		"ESE_WSW": "0",
		"SE_SW": "0",
		"SSE_SSW": "0",
		"S": "1",
		"HORA": "1"
	},
	{
		"LATITUD": "40",
		"MES": "JUN",
		"N": "1",
		"NNE_NNW": "1",
		"NE NW": "1",
		"ENE_WNW": "0",
		"EW": "1",
		"ESE_WSW": "0",
		"SE_SW": "0",
		"SSE_SSW": "-1",
		"S": "-1",
		"HORA": "2"
	},
	{
		"LATITUD": "48",
		"MES": "DIC",
		"N": "-6",
		"NNE_NNW": "-8",
		"NE NW": "-11",
		"ENE_WNW": "-14",
		"EW": "-13",
		"ESE_WSW": "-10",
		"SE_SW": "-3",
		"SSE_SSW": "2",
		"S": "6",
		"HORA": "-25"
	},
	{
		"LATITUD": "48",
		"MES": "ENE/NOV",
		"N": "-6",
		"NNE_NNW": "-8",
		"NE NW": "-11",
		"ENE_WNW": "-13",
		"EW": "-11",
		"ESE_WSW": "-8",
		"SE_SW": "-1",
		"SSE_SSW": "5",
		"S": "8",
		"HORA": "-24"
	},
	{
		"LATITUD": "48",
		"MES": "FEB/OCT",
		"N": "-5",
		"NNE_NNW": "-7",
		"NE NW": "-10",
		"ENE_WNW": "-11",
		"EW": "-8",
		"ESE_WSW": "-5",
		"SE_SW": "1",
		"SSE_SSW": "8",
		"S": "11",
		"HORA": "-18"
	},
	{
		"LATITUD": "48",
		"MES": "MAR/SEP",
		"N": "-4",
		"NNE_NNW": "-6",
		"NE NW": "-6",
		"ENE_WNW": "-7",
		"EW": "-4",
		"ESE_WSW": "-1",
		"SE_SW": "4",
		"SSE_SSW": "8",
		"S": "11",
		"HORA": "-11"
	},
	{
		"LATITUD": "48",
		"MES": "ABR/AGO",
		"N": "-3",
		"NNE_NNW": "-3",
		"NE NW": "-3",
		"ENE_WNW": "-3",
		"EW": "-1",
		"ESE_WSW": "0",
		"SE_SW": "4",
		"SSE_SSW": "6",
		"S": "7",
		"HORA": "-5"
	},
	{
		"LATITUD": "48",
		"MES": "MAY/JUL",
		"N": "0",
		"NNE_NNW": "-1",
		"NE NW": "0",
		"ENE_WNW": "0",
		"EW": "1",
		"ESE_WSW": "1",
		"SE_SW": "3",
		"SSE_SSW": "3",
		"S": "4",
		"HORA": "0"
	},
	{
		"LATITUD": "48",
		"MES": "JUN",
		"N": "1",
		"NNE_NNW": "1",
		"NE NW": "2",
		"ENE_WNW": "1",
		"EW": "2",
		"ESE_WSW": "1",
		"SE_SW": "2",
		"SSE_SSW": "2",
		"S": "3",
		"HORA": "2"
	},
	{
		"LATITUD": "56",
		"MES": "DIC",
		"N": "-7",
		"NNE_NNW": "-9",
		"NE NW": "-12",
		"ENE_WNW": "-16",
		"EW": "-16",
		"ESE_WSW": "-14",
		"SE_SW": "-9",
		"SSE_SSW": "-5",
		"S": "-3",
		"HORA": "-28"
	},
	{
		"LATITUD": "56",
		"MES": "ENE/NOV",
		"N": "-6",
		"NNE_NNW": "-8",
		"NE NW": "-11",
		"ENE_WNW": "-15",
		"EW": "-14",
		"ESE_WSW": "-12",
		"SE_SW": "-6",
		"SSE_SSW": "-1",
		"S": "2",
		"HORA": "-27"
	},
	{
		"LATITUD": "56",
		"MES": "FEB/OCT",
		"N": "-6",
		"NNE_NNW": "-8",
		"NE NW": "-10",
		"ENE_WNW": "-12",
		"EW": "-10",
		"ESE_WSW": "-7",
		"SE_SW": "0",
		"SSE_SSW": "6",
		"S": "9",
		"HORA": "-22"
	},
	{
		"LATITUD": "56",
		"MES": "MAR/SEP",
		"N": "-5",
		"NNE_NNW": "-6",
		"NE NW": "-7",
		"ENE_WNW": "-8",
		"EW": "-5",
		"ESE_WSW": "-2",
		"SE_SW": "4",
		"SSE_SSW": "8",
		"S": "12",
		"HORA": "-15"
	},
	{
		"LATITUD": "56",
		"MES": "ABR/AGO",
		"N": "-3",
		"NNE_NNW": "-4",
		"NE NW": "-4",
		"ENE_WNW": "-4",
		"EW": "-1",
		"ESE_WSW": "1",
		"SE_SW": "5",
		"SSE_SSW": "7",
		"S": "9",
		"HORA": "-8"
	},
	{
		"LATITUD": "56",
		"MES": "MAY/JUL",
		"N": "0",
		"NNE_NNW": "0",
		"NE NW": "0",
		"ENE_WNW": "0",
		"EW": "2",
		"ESE_WSW": "2",
		"SE_SW": "5",
		"SSE_SSW": "6",
		"S": "7",
		"HORA": "-2"
	},
	{
		"LATITUD": "56",
		"MES": "JUN",
		"N": "2",
		"NNE_NNW": "1",
		"NE NW": "2",
		"ENE_WNW": "1",
		"EW": "3",
		"ESE_WSW": "3",
		"SE_SW": "4",
		"SSE_SSW": "5",
		"S": "6",
		"HORA": "1"
	}
]