export default [
  {
    vidrio: 'vidrio sencillo',
    tipo_de_vidrio: 'claro',
    espesor_nominal: '3/32 a 1/4',
    transmision_solar: '0.87-0.80',
    sin_sombreado_interior: '1.00',
    perciana_venecianas_medio: '0.64',
    perciana_venecianas_claro: '0.55',
    percianas_enrollables_opacas_oscuro: '0.59',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.25',
    percianas_enrollables_traslucidas_claro: '0.39'
  },
  {
    vidrio: 'vidrio sencillo',
    tipo_de_vidrio: 'claro',
    espesor_nominal: '1/4 a 1/2',
    transmision_solar: '0.80-0.71',
    sin_sombreado_interior: '0.94',
    perciana_venecianas_medio: '0.64',
    perciana_venecianas_claro: '0.55',
    percianas_enrollables_opacas_oscuro: '0.59',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.25',
    percianas_enrollables_traslucidas_claro: '0.39'
  },
  {
    vidrio: 'vidrio sencillo',
    tipo_de_vidrio: 'claro',
    espesor_nominal: '3/8',
    transmision_solar: '0.72',
    sin_sombreado_interior: '0.90',
    perciana_venecianas_medio: '0.64',
    perciana_venecianas_claro: '0.55',
    percianas_enrollables_opacas_oscuro: '0.59',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.25',
    percianas_enrollables_traslucidas_claro: '0.39'
  },
  {
    vidrio: 'vidrio sencillo',
    tipo_de_vidrio: 'claro',
    espesor_nominal: '1/2',
    transmision_solar: '0.67',
    sin_sombreado_interior: '0.87',
    perciana_venecianas_medio: '0.64',
    perciana_venecianas_claro: '0.55',
    percianas_enrollables_opacas_oscuro: '0.59',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.25',
    percianas_enrollables_traslucidas_claro: '0.39'
  },
  {
    vidrio: 'vidrio sencillo',
    tipo_de_vidrio: 'claro con figuras',
    espesor_nominal: '1/8 a 9/32',
    transmision_solar: '0.87-0.79',
    sin_sombreado_interior: '0.83',
    perciana_venecianas_medio: '0.64',
    perciana_venecianas_claro: '0.55',
    percianas_enrollables_opacas_oscuro: '0.59',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.25',
    percianas_enrollables_traslucidas_claro: '0.39'
  },
  {
    vidrio: 'vidrio sencillo',
    tipo_de_vidrio: 'absorbente de calor con figuras',
    espesor_nominal: '1/8',
    transmision_solar: '-',
    sin_sombreado_interior: '0.83',
    perciana_venecianas_medio: '0.64',
    perciana_venecianas_claro: '0.55',
    percianas_enrollables_opacas_oscuro: '0.59',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.25',
    percianas_enrollables_traslucidas_claro: '0.39'
  },
  {
    vidrio: 'vidrio sencillo',
    tipo_de_vidrio: 'absorbente de calor',
    espesor_nominal: '3/16 a 1/4',
    transmision_solar: '0.46',
    sin_sombreado_interior: '0.69',
    perciana_venecianas_medio: '0.64',
    perciana_venecianas_claro: '0.55',
    percianas_enrollables_opacas_oscuro: '0.59',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.25',
    percianas_enrollables_traslucidas_claro: '0.39'
  },
  {
    vidrio: 'vidrio sencillo',
    tipo_de_vidrio: 'absorbente de calor con figuras',
    espesor_nominal: '3/16 a 1/4',
    transmision_solar: '-',
    sin_sombreado_interior: '0.69',
    perciana_venecianas_medio: '0.57',
    perciana_venecianas_claro: '0.53',
    percianas_enrollables_opacas_oscuro: '0.45',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.30',
    percianas_enrollables_traslucidas_claro: '0.36'
  },
  {
    vidrio: 'vidrio sencillo',
    tipo_de_vidrio: 'coloreado',
    espesor_nominal: '1/8 a 7/32',
    transmision_solar: '0.59-0.45',
    sin_sombreado_interior: '0.69',
    perciana_venecianas_medio: '0.57',
    perciana_venecianas_claro: '0.53',
    percianas_enrollables_opacas_oscuro: '0.45',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.30',
    percianas_enrollables_traslucidas_claro: '0.36'
  },
  {
    vidrio: 'vidrio sencillo',
    tipo_de_vidrio: 'absorbente de calor o con figuras',
    espesor_nominal: '-',
    transmision_solar: '0.44-0.30',
    sin_sombreado_interior: '0.60',
    perciana_venecianas_medio: '0.54',
    perciana_venecianas_claro: '0.52',
    percianas_enrollables_opacas_oscuro: '0.40',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.28',
    percianas_enrollables_traslucidas_claro: '0.32'
  },
  {
    vidrio: 'vidrio sencillo',
    tipo_de_vidrio: 'absorbente de calor',
    espesor_nominal: '3/8',
    transmision_solar: '0.34',
    sin_sombreado_interior: '0.60',
    perciana_venecianas_medio: '0.54',
    perciana_venecianas_claro: '0.52',
    percianas_enrollables_opacas_oscuro: '0.40',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.28',
    percianas_enrollables_traslucidas_claro: '0.32'
  },
  {
    vidrio: 'vidrio sencillo',
    tipo_de_vidrio: 'absorbente de calor o con figuras',
    espesor_nominal: '-',
    transmision_solar: '0.44-0.30',
    sin_sombreado_interior: '0.53',
    perciana_venecianas_medio: '0.42',
    perciana_venecianas_claro: '0.40',
    percianas_enrollables_opacas_oscuro: '0.36',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.28',
    percianas_enrollables_traslucidas_claro: '0.31'
  },
  {
    vidrio: 'vidrio aislante ',
    tipo_de_vidrio: 'claro afuera',
    espesor_nominal: '3/32 a 1/8',
    transmision_solar: '0.71',
    sin_sombreado_interior: '0.88',
    perciana_venecianas_medio: '0.57',
    perciana_venecianas_claro: '0.51',
    percianas_enrollables_opacas_oscuro: '0.60',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.25',
    percianas_enrollables_traslucidas_claro: '0.37'
  },
  {
    vidrio: 'vidrio aislante ',
    tipo_de_vidrio: 'claro adentro',
    espesor_nominal: '-',
    transmision_solar: '-',
    sin_sombreado_interior: '0.88',
    perciana_venecianas_medio: '0.57',
    perciana_venecianas_claro: '0.51',
    percianas_enrollables_opacas_oscuro: '0.60',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.25',
    percianas_enrollables_traslucidas_claro: '0.37'
  },
  {
    vidrio: 'vidrio aislante ',
    tipo_de_vidrio: 'claro afuera',
    espesor_nominal: '-',
    transmision_solar: '0.61',
    sin_sombreado_interior: '0.81',
    perciana_venecianas_medio: '0.57',
    perciana_venecianas_claro: '0.51',
    percianas_enrollables_opacas_oscuro: '0.60',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.25',
    percianas_enrollables_traslucidas_claro: '0.37'
  },
  {
    vidrio: 'vidrio aislante ',
    tipo_de_vidrio: 'claro adentro',
    espesor_nominal: '-',
    transmision_solar: '-',
    sin_sombreado_interior: '0.81',
    perciana_venecianas_medio: '0.57',
    perciana_venecianas_claro: '0.51',
    percianas_enrollables_opacas_oscuro: '0.60',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.25',
    percianas_enrollables_traslucidas_claro: '0.37'
  },
  {
    vidrio: 'vidrio aislante ',
    tipo_de_vidrio: 'absorbente de calor afuera',
    espesor_nominal: '1/4',
    transmision_solar: '0.36',
    sin_sombreado_interior: '0.55',
    perciana_venecianas_medio: '0.57',
    perciana_venecianas_claro: '0.51',
    percianas_enrollables_opacas_oscuro: '0.60',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.25',
    percianas_enrollables_traslucidas_claro: '0.37'
  },
  {
    vidrio: 'vidrio aislante ',
    tipo_de_vidrio: 'claro adentro',
    espesor_nominal: '-',
    transmision_solar: '-',
    sin_sombreado_interior: '0.55',
    perciana_venecianas_medio: '0.39',
    perciana_venecianas_claro: '0.36',
    percianas_enrollables_opacas_oscuro: '0.40',
    'perciana _enrollables_opacas_o_traslucidas_claro': '0.22',
    percianas_enrollables_traslucidas_claro: '0.30'
  },
  {
    vidrio: 'vidrio aislante ',
    tipo_de_vidrio: 'claro',
    espesor_nominal: '-',
    transmision_solar: '-',
    sin_sombreado_interior: '-',
    perciana_venecianas_medio: '-',
    perciana_venecianas_claro: '-',
    percianas_enrollables_opacas_oscuro: '-',
    'perciana _enrollables_opacas_o_traslucidas_claro': '-',
    percianas_enrollables_traslucidas_claro: '-'
  },
  {
    vidrio: 'vidrio aislante ',
    tipo_de_vidrio: 'claro',
    espesor_nominal: '1/4',
    transmision_solar: '-',
    sin_sombreado_interior: '0.71',
    perciana_venecianas_medio: '-',
    perciana_venecianas_claro: '-',
    percianas_enrollables_opacas_oscuro: '-',
    'perciana _enrollables_opacas_o_traslucidas_claro': '-',
    percianas_enrollables_traslucidas_claro: '-'
  },
  {
    vidrio: 'vidrio aislante ',
    tipo_de_vidrio: 'claro',
    espesor_nominal: '1/8',
    transmision_solar: '-',
    sin_sombreado_interior: '0.80',
    perciana_venecianas_medio: '-',
    perciana_venecianas_claro: '-',
    percianas_enrollables_opacas_oscuro: '-',
    'perciana _enrollables_opacas_o_traslucidas_claro': '-',
    percianas_enrollables_traslucidas_claro: '-'
  }
]
